version: 2.1
docker:
  - image: circleci/node:12
orbs:
  browser-tools: circleci/browser-tools@1.1.1
  node: circleci/node@3.0.0
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  test:
    docker:
      - image: 'cimg/node:13.12-browser'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
workflows:
  node-tests:
    jobs:
      - node/test
